baseURL = "https://toolbox.opennms.eu"
languageCode = "en-us"
title = "OpenNMS Toolbox"
theme = "slate"

[ params ]
BackgroundStyle = "#000000;"
OpenLinksInNewWindow = true
Favicon = "favicon.ico"

# list of nav tags
[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "Tools"
tag = "tools"
icon = "wrench"

[[ params.nav ]]
name = "Docs"
tag = "docs"
icon = "book"

[[ params.nav ]]
name = "communication"
tag = "communication"
icon = "comments"

[[ params.nav ]]
name = "Paste"
tag = "paste"
icon = "share"
