baseURL = "https://toolbox.opennms.eu"
languageCode = "en-us"
title = "OpenNMS Toolbox"
theme = "slate"

[ params ]
BackgroundImages = [
  "bg/desert.jpg",
  "bg/ulf-airport.jpg",
  "bg/ulf-berlin.jpg",
  "bg/ulf-centos.jpg",
  "bg/ulf-reading.jpg",
  "bg/ulf-view-01.jpg",
  "bg/ulf-view-02.jpg",
  "bg/ulf-view-03.jpg",
  "bg/ulf-view-04.jpg",
  "bg/ulf-view-05.jpg",
  "bg/ulf-view-06.jpg",
  "bg/ulf-with-toys.jpg"
]
BackgroundStyle = "#000000;"
OpenLinksInNewWindow = true
Favicon = "favicon.ico"

# list of nav tags
[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "Tools"
tag = "tools"
icon = "wrench"

[[ params.nav ]]
name = "Docs"
tag = "docs"
icon = "book"

[[ params.nav ]]
name = "communication"
tag = "communication"
icon = "comments"

[[ params.nav ]]
name = "Paste"
tag = "paste"
icon = "share"
